# config.yaml
path: C:\Users\user\PycharmProjects\opencv # Путь к папке с вашим датасетом
train: C:\Users\user\PycharmProjects\opencv\dataset\images # Путь к папке с тренировочными изображениями
val: C:\Users\user\PycharmProjects\opencv\dataset\images # Путь к папке с валидационными изображениями
nc: 2 # Укажите количество классов в вашем датасете
names: ['Roki-2', 'Walker'] # Список с названиями классов